package com.example.melaAttendance.database;

import org.greenrobot.greendao.annotation.Entity;
import org.greenrobot.greendao.annotation.Id;
import org.greenrobot.greendao.annotation.Generated;

@Entity
public class AttendanceFlagData {
    @Id(autoincrement = true)
    private Long autogeneratedFlagId;
    private  String userName;
    private String participantFlag;
    private String shgRegIdAttendanceFlagData;
    private String dateOfAttendanceFlagData;
    private String participantSataus;
    private String melaId;
    private String morningFlag,eeningFlag;

    @Generated(hash = 470040225)
    public AttendanceFlagData(Long autogeneratedFlagId, String userName,
            String participantFlag, String shgRegIdAttendanceFlagData,
            String dateOfAttendanceFlagData, String participantSataus,
            String melaId, String morningFlag, String eeningFlag) {
        this.autogeneratedFlagId = autogeneratedFlagId;
        this.userName = userName;
        this.participantFlag = participantFlag;
        this.shgRegIdAttendanceFlagData = shgRegIdAttendanceFlagData;
        this.dateOfAttendanceFlagData = dateOfAttendanceFlagData;
        this.participantSataus = participantSataus;
        this.melaId = melaId;
        this.morningFlag = morningFlag;
        this.eeningFlag = eeningFlag;
    }
    @Generated(hash = 1243694896)
    public AttendanceFlagData() {
    }
    public Long getAutogeneratedFlagId() {
        return this.autogeneratedFlagId;
    }
    public void setAutogeneratedFlagId(Long autogeneratedFlagId) {
        this.autogeneratedFlagId = autogeneratedFlagId;
    }
    public String getUserName() {
        return this.userName;
    }
    public void setUserName(String userName) {
        this.userName = userName;
    }
    public String getParticipantFlag() {
        return this.participantFlag;
    }
    public void setParticipantFlag(String participantFlag) {
        this.participantFlag = participantFlag;
    }
    public String getShgRegIdAttendanceFlagData() {
        return this.shgRegIdAttendanceFlagData;
    }
    public void setShgRegIdAttendanceFlagData(String shgRegIdAttendanceFlagData) {
        this.shgRegIdAttendanceFlagData = shgRegIdAttendanceFlagData;
    }
    public String getDateOfAttendanceFlagData() {
        return this.dateOfAttendanceFlagData;
    }
    public void setDateOfAttendanceFlagData(String dateOfAttendanceFlagData) {
        this.dateOfAttendanceFlagData = dateOfAttendanceFlagData;
    }
    public String getParticipantSataus() {
        return this.participantSataus;
    }
    public void setParticipantSataus(String participantSataus) {
        this.participantSataus = participantSataus;
    }
    public String getMelaId() {
        return this.melaId;
    }
    public void setMelaId(String melaId) {
        this.melaId = melaId;
    }
    public String getMorningFlag() {
        return this.morningFlag;
    }
    public void setMorningFlag(String morningFlag) {
        this.morningFlag = morningFlag;
    }
    public String getEeningFlag() {
        return this.eeningFlag;
    }
    public void setEeningFlag(String eeningFlag) {
        this.eeningFlag = eeningFlag;
    }

}
