package com.example.melaAttendance.database;

import org.greenrobot.greendao.annotation.Entity;
import org.greenrobot.greendao.annotation.Id;
import org.greenrobot.greendao.annotation.Generated;
@Entity
public class SelectedProductDetails {
    @Id(autoincrement = true)
    private Long  autoGeneratedProductId;
    private String  productId;
    private String productName;
    private String productQuantity;
    private String productUnitPrice;
    private String productTotalPrice;
    @Generated(hash = 1218988714)
    public SelectedProductDetails(Long autoGeneratedProductId, String productId,
            String productName, String productQuantity, String productUnitPrice,
            String productTotalPrice) {
        this.autoGeneratedProductId = autoGeneratedProductId;
        this.productId = productId;
        this.productName = productName;
        this.productQuantity = productQuantity;
        this.productUnitPrice = productUnitPrice;
        this.productTotalPrice = productTotalPrice;
    }
    @Generated(hash = 1998882800)
    public SelectedProductDetails() {
    }
    public Long getAutoGeneratedProductId() {
        return this.autoGeneratedProductId;
    }
    public void setAutoGeneratedProductId(Long autoGeneratedProductId) {
        this.autoGeneratedProductId = autoGeneratedProductId;
    }
    public String getProductId() {
        return this.productId;
    }
    public void setProductId(String productId) {
        this.productId = productId;
    }
    public String getProductName() {
        return this.productName;
    }
    public void setProductName(String productName) {
        this.productName = productName;
    }
    public String getProductQuantity() {
        return this.productQuantity;
    }
    public void setProductQuantity(String productQuantity) {
        this.productQuantity = productQuantity;
    }
    public String getProductUnitPrice() {
        return this.productUnitPrice;
    }
    public void setProductUnitPrice(String productUnitPrice) {
        this.productUnitPrice = productUnitPrice;
    }
    public String getProductTotalPrice() {
        return this.productTotalPrice;
    }
    public void setProductTotalPrice(String productTotalPrice) {
        this.productTotalPrice = productTotalPrice;
    }
}
